repos:

- repo: local
  hooks:
  
  - id: generate-init
    name: Generates __init__.py files
    language: python
    entry: python hooks/generate_init.py
    always_run: true
    require_serial: true 
    additional_dependencies: ["mkinit", "ruff"]

  - id: fix-line-endings
    name: Convert CRLF/CR endings to LF
    language: python
    require_serial: true 
    entry: python hooks/fix_line_endings.py
    types: ["text"]
    
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-executables-have-shebangs
  - id: check-symlinks

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.4.6
  hooks:
    #Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi, jupyter ]
    #Run the linter.
    - id: ruff
      types_or: [ python, pyi, jupyter ]
      args: [ --fix, --exit-non-zero-on-fix ]