repos:

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.275
  hooks:
    - id: ruff
      args: [ --fix, --exit-non-zero-on-fix ]

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort (python)

-   repo: https://github.com/psf/black.git
    rev: 23.1.0
    hooks:
    - id: black
      language_version: python3.9

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: end-of-file-fixer
  - id: fix-encoding-pragma
  - id: trailing-whitespace
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-symlinks
  - id: debug-statements
  - id: mixed-line-ending
