repos:


- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort
      name: isort (python)

-   repo: https://github.com/psf/black.git
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3.9

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: end-of-file-fixer
  - id: fix-encoding-pragma
  - id: trailing-whitespace
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-symlinks
  - id: debug-statements
  - id: mixed-line-ending
