"""
This type stub file was generated by pyright.
"""

"""
Table of energy-dependent neutron cross-sections.

dict(("element", isotope or None): [[energy (eV), Re(a), Im(a), |a|], ...])

From Lynn and Seeger (1990)
"""
from __future__ import annotations

ENERGY_DEPENDENT_TABLES = ...
