name: Python package

on: [push]

env:
  UV_SYSTEM_PYTHON: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Run pre-commit checks
        run: |
          uv pip install pre-commit
          pre-commit install 
          pre-commit run --all-files

      - name: Install dependencies
        run: |
          uv pip install pytest pytest-cov hypothesis .[CI]

      - name: Test with pytest
        run: |
          pytest --cov=prepper --cov-report=xml --cov-report=html
